### ISSUE TITLE
No copyright in code file headers

### ISSUE THREAD

**Issue by JohnPersano** [JohnPersano/Beer_Buddy#1]
There are no copyright notices in the code header files.

**Comment by gsheehan22** [comment]
Headers in all source files should follow the format specified in our Software Development Plan (see section 5.3.1). A sample is provided for reference below:

/*
 * Project: Beer Buddy Application
 * Filename: Sample.java
 * Author: John Smith
 * Date Created: 02/15/2017
 * Description: Model for Sample class
 * Copyright (c) 2017, Beer Buddies Inc. All Rights Reserved
 *
*/

**Comment by JohnPersano** [comment]
See https://github.com/JohnPersano/Beer_Buddy/issues/5#issuecomment-298263725

**Comment by JohnPersano** [comment]
Addressed in: https://github.com/JohnPersano/Beer_Buddy/releases/tag/RC1.0.0

@gsheehan22 please verify and I will close the issue.

**Comment by gsheehan22** [comment]
@JohnPersano 

Changes verified. Thanks again!

**Comment by JohnPersano** [comment]
Updates verified, closing issue.
