### ISSUE TITLE
Javadoc references missing

### ISSUE THREAD

**Issue by gsheehan22** [JohnPersano/Beer_Buddy#5]
The file below does not contain Javadoc references for each method as specified in our software development plan:

https://github.com/JohnPersano/Beer_Buddy/blob/master/app/src/main/java/com/johnpersano/github/beerbuddy/MainActivity.java

**Comment by JohnPersano** [comment]
I will add it before the 1.0.0 RC release.

**Comment by JohnPersano** [comment]
Addressed in: https://github.com/JohnPersano/Beer_Buddy/releases/tag/RC1.0.0

Greg, please verify and I will close the issue.

**Comment by gsheehan22** [comment]
@JohnPersano

Changes verified. Thanks again.

**Comment by JohnPersano** [comment]
Updates verified, closing issue.
